baseURL: "https://priisk1.github.io/h/"
anguageCode: ru-ru
title: "Прииск"
theme: "PaperMod"

params:
  homeInfoParams:
    Title: "Добро пожаловать в «Прииск»"
    Content: "Архивные документы и исторические расследования по Сосерскому горному округу"
  mainSections:
    - pages
  ShowReadingTime: true
  author: "Прииск"
  contact: "ваш-email@example.com"

menu:
  main:
    - identifier: "search"
      name: "Поиск"
      url: "/search/"
      weight: 10
    - identifier: "tags"
      name: "Теги"
      url: "/tags/"
      weight: 20